### ISSUE TITLE
collectsfdata  2.5.7220.40058 issue System.IO.FileLoadException: Could not load file or assembly 'Microsoft.IdentityModel.Clients.ActiveDirectory, Version=4.5.1.0

### ISSUE THREAD

**Issue by jagilber** [microsoft/CollectServiceFabricData#17]
collectsfdata  2.5.7220.40058 issue System.IO.FileLoadException: Could not load file or assembly 'Microsoft.IdentityModel.Clients.ActiveDirectory, Version=4.5.1.0

1:Query:query:.show tables | project TableName | where TableName == 'trace_jagilber_sac'
1:Execute:exception: System.IO.FileLoadException: Could not load file or assembly 'Microsoft.IdentityModel.Clients.ActiveDirectory, Version=4.5.1.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
File name: 'Microsoft.IdentityModel.Clients.ActiveDirectory, Version=4.5.1.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
   at Kusto.Data.Security.HttpClientAuthenticatorFactory.CreateAuthenticator(KustoConnectionStringBuilder kcsb)
   at Kusto.Data.Net.Client.RestClient2..ctor(KustoConnectionStringBuilder kcsb, Boolean canForwardTokenToTarget)
   at Kusto.Data.Net.Client.KustoClientFactory.CreateCslQueryProvider(KustoConnectionStringBuilder builder)
   at CollectSFData.KustoEndpointInfo.Query(String query)
   at CollectSFData.KustoEndpointInfo.HasTable(String tableName)
   at CollectSFData.KustoConnection.Connect()
   at CollectSFData.Program.Execute(String[] args)

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

**Comment by jagilber** [comment]
fixed in #18
